
###ThymeLeaf配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimeZone=Hongkong
    username: root
    password: adkun
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 15
      minimum-idle: 5
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    #prefix：指定模板所在的目录
    prefix: classpath:/templates/
    #check-tempate-location: 检查模板路径是否存在
    check-template-location: true
    #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    cache: false
    suffix:  .html
    encoding: UTF-8
    mode: HTML5

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    useGeneratedKeys: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.adkun.myCommunity.entity

server:
  port: 8081
  servlet:
    context-path: /community
